name: Auto Update Data

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # এখানে পারমিশন অ্যাড করা হয়েছে
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # আপডেট ভার্সন

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libs
        run: pip install requests pycryptodome

      - name: Run Scraper
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_FID: ${{ secrets.FIREBASE_FID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          AES_SECRET: ${{ secrets.AES_SECRET }}
        run: python scraper.py

      - name: Save Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Sportzx.json
          git commit -m "Auto Update: $(date)" || exit 0
          git push
